import { AlertTriangle, BarChart3, BrainCircuit, DatabaseZap, ExternalLink } from 'lucide-react'
import { useConnectedProject } from '../../context/ConnectedProjectContext'
import { useConnectedWorkspace } from '../../hooks/useConnectedWorkspace'
import { analyticsSummary, dataQuality, deriveExceptions, disciplinePerformance, executionKnowledge, progressSeries } from '../../lib/connected-analytics'

type Mode='exceptions'|'performance'|'data-quality'|'execution-knowledge'
interface Props { mode:Mode; onNavigate?:(route:string)=>void }
const title:Record<Mode,string>={'exceptions':'Exceptions','performance':'Performance','data-quality':'Data Quality','execution-knowledge':'Execution Knowledge'}
const subtitle:Record<Mode,string>={
  'exceptions':'Deterministic conditions derived from current schedule, actual and evidence records.',
  'performance':'Plan-versus-verified execution, calculated from connected L6 milestone dates.',
  'data-quality':'Transparent completeness ratios; unknown values are excluded rather than invented.',
  'execution-knowledge':'Historical duration evidence from activities with both verified start and finish dates.',
}

function Frame({mode,children}:{mode:Mode;children:React.ReactNode}){return <div className="h-full overflow-auto p-5 sm:p-8"><header className="mb-6"><p className="text-[10px] font-bold uppercase tracking-[.12em]" style={{color:'#F46F29'}}>Connected intelligence</p><h1 className="mt-1 text-[24px] font-bold" style={{color:'var(--c-text)'}}>{title[mode]}</h1><p className="mt-1 max-w-3xl text-[13px]" style={{color:'var(--c-muted)'}}>{subtitle[mode]}</p></header>{children}</div>}
const Empty=({children}:{children:string})=><div className="rounded-[14px] p-8 text-center text-[13px]" style={{background:'var(--c-card)',border:'1px solid var(--c-border)',color:'var(--c-muted)'}}>{children}</div>

export default function ConnectedInsightPage({mode,onNavigate}:Props){
  const access=useConnectedProject();const state=useConnectedWorkspace(access.project!.id)
  if(state.loading)return <Frame mode={mode}><Empty>Loading connected project intelligence…</Empty></Frame>
  if(state.error||!state.workspace)return <Frame mode={mode}><div role="alert" className="rounded-[12px] p-4 text-red-700" style={{background:'rgba(220,38,38,.08)'}}>{state.error||'Project intelligence is unavailable.'}</div></Frame>
  const workspace=state.workspace;const asOf=new Date().toISOString().slice(0,10)
  if(mode==='exceptions'){
    const items=deriveExceptions(workspace,asOf)
    return <Frame mode={mode}>{items.length===0?<Empty>No deterministic exceptions are present in the connected project snapshot.</Empty>:<div className="space-y-3">{items.map(item=><article key={item.id} className="rounded-[13px] p-4" style={{background:'var(--c-card)',border:`1px solid ${item.severity==='critical'?'rgba(220,38,38,.3)':'var(--c-border)'}`}}><div className="flex items-start gap-3"><AlertTriangle size={17} style={{color:item.severity==='critical'?'#DC2626':'#D97706'}}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-[14px] font-semibold" style={{color:'var(--c-text)'}}>{item.title}</h2><span className="rounded px-2 py-0.5 text-[10px] font-bold uppercase" style={{background:item.severity==='critical'?'rgba(220,38,38,.1)':'rgba(217,119,6,.1)',color:item.severity==='critical'?'#DC2626':'#B45309'}}>{item.severity}</span></div><p className="mt-1 text-[12px]" style={{color:'var(--c-muted)'}}>{item.detail}</p><p className="mt-2 text-[11px]" style={{color:'var(--c-subtle)'}}>{[item.discipline,item.area].filter(Boolean).join(' · ')||'Evidence workflow'}</p></div><button onClick={()=>onNavigate?.(item.eventId?'review-queue':'schedule')} aria-label="Open source workflow"><ExternalLink size={15} style={{color:'#F46F29'}}/></button></div></article>)}</div>}</Frame>
  }
  if(mode==='data-quality'){
    const metrics=dataQuality(workspace)
    return <Frame mode={mode}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{metrics.map(metric=><article key={metric.label} className="rounded-[14px] p-5" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><DatabaseZap size={17} style={{color:'#F46F29'}}/><h2 className="mt-3 text-[13px] font-semibold" style={{color:'var(--c-text)'}}>{metric.label}</h2><div className="mt-2 text-[28px] font-bold" style={{color:'var(--c-text)'}}>{metric.value===null?'Not available':`${metric.value}%`}</div>{metric.value!==null&&<div className="mt-3 h-1.5 overflow-hidden rounded-full" style={{background:'var(--c-border)'}}><div className="h-full rounded-full" style={{width:`${metric.value}%`,background:'#F46F29'}}/></div>}<p className="mt-3 text-[11px]" style={{color:'var(--c-muted)'}}>{metric.detail}</p></article>)}</div></Frame>
  }
  if(mode==='execution-knowledge'){
    const knowledge=executionKnowledge(workspace)
    return <Frame mode={mode}><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-[14px] p-5" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><BrainCircuit size={18} style={{color:'#F46F29'}}/><p className="mt-3 text-[11px] uppercase" style={{color:'var(--c-subtle)'}}>Completed verified samples</p><div className="text-[30px] font-bold" style={{color:'var(--c-text)'}}>{knowledge.samples.length}</div></article><article className="rounded-[14px] p-5" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><p className="text-[11px] uppercase" style={{color:'var(--c-subtle)'}}>Average duration</p><div className="mt-2 text-[22px] font-bold" style={{color:'var(--c-text)'}}>{knowledge.averageActualDays===null?'Not available':`${knowledge.averageActualDays} days actual`}</div><p className="mt-1 text-[12px]" style={{color:'var(--c-muted)'}}>{knowledge.averagePlannedDays===null?'No comparable planned duration.':`${knowledge.averagePlannedDays} days planned.`}</p></article></div>{knowledge.samples.length===0?<div className="mt-4"><Empty>Insights require activities with verified actual starts and finishes. No prediction is shown without evidence.</Empty></div>:<div className="mt-5 overflow-x-auto rounded-[14px]" style={{border:'1px solid var(--c-border)'}}><table className="w-full text-left text-[12px]"><thead style={{background:'var(--c-card)',color:'var(--c-subtle)'}}><tr>{['Activity','Discipline','Planned days','Actual days'].map(label=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{knowledge.samples.map(sample=><tr key={sample.activityId} style={{borderTop:'1px solid var(--c-border)'}}><td className="px-4 py-3 font-semibold" style={{color:'var(--c-text)'}}>{sample.externalId}</td><td className="px-4 py-3">{sample.discipline}</td><td className="px-4 py-3">{sample.plannedDays}</td><td className="px-4 py-3">{sample.actualDays}</td></tr>)}</tbody></table></div>}</Frame>
  }
  const summary=analyticsSummary(workspace,asOf),disciplines=disciplinePerformance(workspace,asOf),series=progressSeries(workspace,asOf)
  const metrics=[['Plan',summary.plan],['Execution',summary.actual],['Variance',summary.variance],['Started late',summary.startedLate],['Finished late',summary.finishedLate],['Needs review',summary.needsReview]] as const
  return <Frame mode={mode}><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{metrics.map(([label,value])=><article key={label} className="rounded-[13px] p-4" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><p className="text-[10px] font-bold uppercase" style={{color:'var(--c-subtle)'}}>{label}</p><p className="mt-2 text-[24px] font-bold" style={{color:'var(--c-text)'}}>{value===null?'—':typeof value==='number'&&['Plan','Execution','Variance'].includes(label)?`${value}%`:value}</p></article>)}</section><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><article className="rounded-[14px] p-5" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><h2 className="text-[14px] font-semibold" style={{color:'var(--c-text)'}}>Plan vs verified execution</h2><div className="mt-5 flex h-52 items-end gap-2">{series.map(point=><div key={point.date} className="flex h-full min-w-0 flex-1 items-end justify-center gap-1" title={`${point.date}: plan ${point.plan}%, actual ${point.actual}%`}><div className="w-2 rounded-t" style={{height:`${Math.max(point.plan,2)}%`,background:'var(--c-border-strong)'}}/><div className="w-2 rounded-t" style={{height:`${Math.max(point.actual,2)}%`,background:'#F46F29'}}/></div>)}</div><div className="mt-2 flex justify-between text-[9px]" style={{color:'var(--c-subtle)'}}>{series.map(point=><span key={point.date}>{point.label}</span>)}</div></article><article className="rounded-[14px] p-5" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><h2 className="flex items-center gap-2 text-[14px] font-semibold" style={{color:'var(--c-text)'}}><BarChart3 size={16} style={{color:'#F46F29'}}/>Discipline performance</h2><div className="mt-4 space-y-4">{disciplines.map(item=><div key={item.name}><div className="flex justify-between text-[11px]"><span style={{color:'var(--c-text)'}}>{item.name} · {item.activities}</span><span style={{color:item.variance<0?'#DC2626':'#16A34A'}}>{item.variance}%</span></div><div className="mt-1 h-1.5 rounded-full" style={{background:'var(--c-border)'}}><div className="h-full rounded-full" style={{width:`${item.actual}%`,background:'#F46F29'}}/></div></div>)}</div></article></div></Frame>
}
