import { useMemo, useState } from 'react'
import { CheckCircle2, Plus, RefreshCw, Search } from 'lucide-react'
import { useConnectedProject } from '../../context/ConnectedProjectContext'
import { useConnectedWorkspace } from '../../hooks/useConnectedWorkspace'
import { displayDate, scheduleStatus, verifiedActualRows } from '../../lib/real-schedule'

interface Props { onSelectActual: (id: string) => void; onCaptureProgress: () => void }

export default function ActualsPage({ onSelectActual, onCaptureProgress }: Props) {
  const access = useConnectedProject()
  const projectId = access.project!.id
  const { workspace, loading, error, refresh } = useConnectedWorkspace(projectId)
  const [search, setSearch] = useState('')
  const [discipline, setDiscipline] = useState('')
  const [area, setArea] = useState('')
  const rows = useMemo(() => verifiedActualRows(projectId, workspace?.activities ?? [], workspace?.actuals ?? []).filter(({ activity }) => {
    const text = [activity.external_id, activity.name, activity.discipline, activity.area, activity.equipment_ref].filter(Boolean).join(' ').toLowerCase()
    return (!search || text.includes(search.toLowerCase())) && (!discipline || activity.discipline === discipline) && (!area || activity.area === area)
  }), [projectId, workspace, search, discipline, area])
  const disciplines = useMemo(() => [...new Set((workspace?.activities ?? []).flatMap(a => a.discipline ? [a.discipline] : []))].sort(), [workspace])
  const areas = useMemo(() => [...new Set((workspace?.activities ?? []).flatMap(a => a.area ? [a.area] : []))].sort(), [workspace])

  return <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
    <header className="shrink-0 border-b px-7 py-5" style={{ background: 'var(--c-page)', borderColor: 'var(--c-border)' }}><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.08em]" style={{ color: '#F46F29' }}>{access.project?.name}</p><h1 className="text-[22px] font-bold" style={{ color: 'var(--c-text)' }}>Verified Actuals</h1><p className="text-[13px]" style={{ color: 'var(--c-muted)' }}>Persisted schedule dates created through human review.</p></div><div className="flex gap-2"><button onClick={() => void refresh()} aria-label="Refresh actuals" className="flex h-9 w-9 items-center justify-center rounded-[9px]" style={{ border: '1px solid var(--c-border)', color: 'var(--c-muted)', background: 'var(--c-card)' }}><RefreshCw size={14} /></button><button onClick={onCaptureProgress} className="flex h-9 items-center gap-2 rounded-[9px] px-4 text-[12px] font-bold text-white" style={{ background: '#F46F29' }}><Plus size={14} />Capture progress</button></div></div>
      <div className="mt-5 flex flex-wrap gap-2"><div className="relative"><Search size={13} className="absolute left-3 top-2.5" color="var(--c-muted)" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search verified actuals" className="h-8 w-56 rounded-[8px] pl-8 pr-3 text-[12px] outline-none" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)', color: 'var(--c-text)' }} /></div><select value={discipline} onChange={event => setDiscipline(event.target.value)} className="h-8 rounded-[8px] px-3 text-[12px]" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)', color: 'var(--c-text)' }}><option value="">All disciplines</option>{disciplines.map(value => <option key={value}>{value}</option>)}</select><select value={area} onChange={event => setArea(event.target.value)} className="h-8 rounded-[8px] px-3 text-[12px]" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)', color: 'var(--c-text)' }}><option value="">All areas</option>{areas.map(value => <option key={value}>{value}</option>)}</select>{!loading && workspace && <span className="ml-auto self-center text-[12px]" style={{ color: 'var(--c-muted)' }}>{verifiedActualRows(projectId, workspace.activities, workspace.actuals).length} activities with verified dates</span>}</div>
    </header>
    {loading && <div className="p-12 text-center text-[13px]" style={{ color: 'var(--c-muted)' }}>Loading verified actuals…</div>}
    {!loading && error && <div role="alert" className="m-7 rounded-[12px] p-5 text-[13px]" style={{ background: '#FEF2F2', color: '#B91C1C' }}>{error}<button onClick={() => void refresh()} className="ml-3 font-bold underline">Retry</button></div>}
    {!loading && !error && workspace && <div className="min-h-0 flex-1 overflow-auto"><table className="w-full text-left" style={{ minWidth: 900, borderCollapse: 'collapse' }}><thead className="sticky top-0 z-10" style={{ background: 'var(--c-page)' }}><tr>{['Activity','Level','Discipline / Area','Verified actual start','Verified actual finish','Status'].map(label => <th key={label} className="border-b px-5 py-3 text-[10px] font-bold uppercase tracking-[.08em]" style={{ borderColor: 'var(--c-border)', color: 'var(--c-subtle)' }}>{label}</th>)}</tr></thead><tbody>{rows.map(({ id, activity, actual }) => <tr key={id} onClick={() => onSelectActual(id)} className="cursor-pointer border-b" style={{ borderColor: 'var(--c-border)' }}><td className="px-5 py-4"><strong className="block text-[11px]" style={{ color: '#F46F29', fontFamily: 'var(--font-data)' }}>{activity.external_id}</strong><span className="text-[13px] font-semibold" style={{ color: 'var(--c-text)' }}>{activity.name}</span></td><td className="px-5 py-4 text-[12px]" style={{ color: 'var(--c-text)' }}>{activity.level}</td><td className="px-5 py-4 text-[12px]" style={{ color: 'var(--c-muted)' }}>{activity.discipline ?? 'Not reported'}<br />{activity.area ?? 'Not reported'}</td><td className="px-5 py-4 text-[12px] font-semibold" style={{ color: actual.actual_start ? 'var(--c-text)' : 'var(--c-subtle)' }}>{actual.actual_start ? <span className="inline-flex items-center gap-1.5">{displayDate(actual.actual_start)}<CheckCircle2 size={12} color="#16A34A" /></span> : <i>Not reported</i>}</td><td className="px-5 py-4 text-[12px] font-semibold" style={{ color: actual.actual_finish ? 'var(--c-text)' : 'var(--c-subtle)' }}>{actual.actual_finish ? <span className="inline-flex items-center gap-1.5">{displayDate(actual.actual_finish)}<CheckCircle2 size={12} color="#16A34A" /></span> : <i>Not reported</i>}</td><td className="px-5 py-4"><span className="rounded-full px-2 py-1 text-[11px] font-semibold" style={{ background: actual.actual_finish ? 'rgba(22,163,74,.10)' : 'rgba(244,111,41,.11)', color: actual.actual_finish ? '#15803D' : '#C2410C' }}>{scheduleStatus(actual)}</span></td></tr>)}</tbody></table>{!rows.length && <div className="p-12 text-center"><h2 className="text-[16px] font-bold" style={{ color: 'var(--c-text)' }}>No verified actuals</h2><p className="mt-1 text-[13px]" style={{ color: 'var(--c-muted)' }}>No persisted actual dates match this view.</p></div>}</div>}
  </div>
}
