import { useMemo, useState } from 'react'
import { ArrowLeft, FileSearch, Search, Upload } from 'lucide-react'
import { useConnectedProject } from '../context/ConnectedProjectContext'
import { useConnectedWorkspace } from '../hooks/useConnectedWorkspace'
import type { IngestedReport } from '../lib/connected-types'
import { canCaptureProgress } from '../lib/manual-capture'

interface Props { onUpload:()=>void; refreshKey:number; onReview:()=>void }
const fmt=(date:string)=>new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(`${date.slice(0,10)}T00:00:00Z`))

export default function ConnectedReports({onUpload,refreshKey,onReview}:Props){
  const access=useConnectedProject()
  const state=useConnectedWorkspace(access.project!.id)
  const [query,setQuery]=useState('')
  const [selected,setSelected]=useState<string|null>(null)
  const workspace=state.workspace
  const reports=useMemo(()=>workspace?.reports??[],[workspace,refreshKey])
  const visible=reports.filter(report=>(report.filename??'manual field update').toLowerCase().includes(query.toLowerCase())||report.report_date.includes(query))
  const report=reports.find(item=>item.id===selected)

  if(report&&workspace){
    const events=workspace.events.filter(event=>event.report_id===report.id)
    return <div className="h-full overflow-auto p-5 sm:p-8">
      <button onClick={()=>setSelected(null)} className="flex items-center gap-2 text-[12px] font-semibold" style={{color:'#F46F29'}}><ArrowLeft size={14}/>Back to reports</button>
      <header className="mt-5"><p className="text-[10px] font-bold uppercase tracking-[.12em]" style={{color:'#F46F29'}}>Report analysis</p><h1 className="mt-1 text-[24px] font-bold" style={{color:'var(--c-text)'}}>{report.filename??'Manual field update'}</h1><p className="mt-1 text-[12px]" style={{color:'var(--c-muted)'}}>{fmt(report.report_date)} · {report.extraction_method??'manual'} extraction · SHA-256 {report.source_sha256?.slice(0,12)??'not applicable'}{report.source_sha256?'…':''}</p></header>
      <section className="mt-6 grid gap-3 sm:grid-cols-3">{[['Processing',report.processing_status??'processed'],['Events found',events.length],['Pending review',events.filter(event=>event.review_status==='pending').length]].map(([label,value])=><div key={label} className="rounded-[13px] p-4" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><p className="text-[10px] font-bold uppercase" style={{color:'var(--c-subtle)'}}>{label}</p><p className="mt-2 text-[20px] font-bold capitalize" style={{color:'var(--c-text)'}}>{value}</p></div>)}</section>
      <details className="mt-5 rounded-[13px] p-4" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><summary className="cursor-pointer text-[13px] font-semibold" style={{color:'var(--c-text)'}}>View extracted source text</summary><pre className="mt-4 max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-[9px] p-4 text-[11px] leading-5" style={{background:'var(--c-page)',color:'var(--c-muted)'}}>{report.raw_text}</pre></details>
      <section className="mt-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-[15px] font-semibold" style={{color:'var(--c-text)'}}>Extracted evidence</h2>{events.some(event=>event.review_status==='pending')&&<button onClick={onReview} className="rounded-[8px] px-3 py-2 text-[12px] font-semibold" style={{background:'var(--c-brand-tint)',color:'#F46F29'}}>Open Review Queue</button>}</div>
        {events.length===0?<p className="rounded-[13px] p-6 text-[13px]" style={{background:'var(--c-card)',border:'1px solid var(--c-border)',color:'var(--c-muted)'}}>No execution statements were extracted. The source remains recorded without inventing candidate events.</p>:<div className="space-y-3">{events.map(event=><article key={event.id} className="rounded-[13px] p-4" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><div className="flex flex-wrap items-center gap-2"><span className="rounded px-2 py-1 text-[10px] font-bold uppercase" style={{background:event.review_status==='verified'?'rgba(22,163,74,.1)':'rgba(217,119,6,.1)',color:event.review_status==='verified'?'#16A34A':'#B45309'}}>{event.review_status}</span><span className="text-[11px] font-semibold uppercase" style={{color:'var(--c-muted)'}}>{event.event_type.replace('_',' ')}</span><span className="text-[11px]" style={{color:'var(--c-subtle)'}}>{event.actual_date??'date not reported'}</span></div><blockquote className="mt-3 border-l-2 pl-3 text-[13px]" style={{borderColor:'#F46F29',color:'var(--c-text)'}}>“{event.source_quote}”</blockquote><dl className="mt-3 grid gap-2 text-[11px] sm:grid-cols-3"><div><dt style={{color:'var(--c-subtle)'}}>Source location</dt><dd style={{color:'var(--c-text)'}}>{event.source_location??'Not available'}</dd></div><div><dt style={{color:'var(--c-subtle)'}}>Suggested activity</dt><dd style={{color:'var(--c-text)'}}>{workspace.activities.find(activity=>activity.id===event.suggested_activity_id)?.external_id??'No suggestion'}</dd></div><div><dt style={{color:'var(--c-subtle)'}}>Advisory confidence</dt><dd style={{color:'var(--c-text)'}}>{event.confidence==null?'Not available':`${Math.round(event.confidence*100)}%`}</dd></div></dl></article>)}</div>}
      </section>
    </div>
  }

  return <div className="flex h-full flex-col overflow-hidden">
    <header className="shrink-0 border-b p-5 sm:px-8 sm:py-6" style={{borderColor:'var(--c-border)'}}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em]" style={{color:'#F46F29'}}>Evidence ingestion</p><h1 className="mt-1 text-[24px] font-bold" style={{color:'var(--c-text)'}}>Reports</h1><p className="mt-1 text-[13px]" style={{color:'var(--c-muted)'}}>Connected source records and their extracted execution evidence.</p></div>{canCaptureProgress(access.role)&&<button onClick={onUpload} className="flex items-center gap-2 rounded-[9px] px-4 py-2 text-[13px] font-semibold text-white" style={{background:'linear-gradient(135deg,#F46F29,#F59B4C)'}}><Upload size={15}/>Upload report</button>}</div><label className="relative mt-5 block max-w-sm"><Search className="absolute left-3 top-2.5" size={14} style={{color:'var(--c-subtle)'}}/><span className="sr-only">Search reports</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search filename or date" className="w-full rounded-[9px] py-2 pl-9 pr-3 text-[13px]" style={{background:'var(--c-card)',border:'1px solid var(--c-border)',color:'var(--c-text)'}}/></label></header>
    <div className="flex-1 overflow-auto p-5 sm:p-8">{state.loading&&<p className="text-[13px]" style={{color:'var(--c-muted)'}}>Loading connected reports…</p>}{state.error&&<p role="alert" className="text-red-700">{state.error}</p>}{workspace&&visible.length===0&&<div className="rounded-[14px] p-10 text-center" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><FileSearch className="mx-auto" style={{color:'#F46F29'}}/><h2 className="mt-3 text-[15px] font-semibold" style={{color:'var(--c-text)'}}>{reports.length?'No reports match the search':'No reports yet'}</h2><p className="mt-1 text-[12px]" style={{color:'var(--c-muted)'}}>Captured field updates and uploaded sources appear here after migration 004 is applied.</p></div>}
      {visible.length>0&&<div className="overflow-x-auto rounded-[14px]" style={{border:'1px solid var(--c-border)'}}><table className="w-full min-w-[760px] text-left text-[12px]"><thead style={{background:'var(--c-card)',color:'var(--c-subtle)'}}><tr>{['Report','Report date','Format','Processing','Extraction','Events'].map(label=><th key={label} className="px-4 py-3 uppercase tracking-wide">{label}</th>)}</tr></thead><tbody>{visible.map((item:IngestedReport)=>{const count=workspace!.events.filter(event=>event.report_id===item.id).length;return <tr key={item.id} tabIndex={0} role="button" onClick={()=>setSelected(item.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(item.id)}}} className="cursor-pointer" style={{borderTop:'1px solid var(--c-border)'}}><td className="px-4 py-3 font-semibold" style={{color:'var(--c-text)'}}>{item.filename??'Manual field update'}</td><td className="px-4 py-3">{fmt(item.report_date)}</td><td className="px-4 py-3">{item.media_type??'text entry'}</td><td className="px-4 py-3 capitalize">{item.processing_status??'processed'}</td><td className="px-4 py-3 capitalize">{item.extraction_method??'manual'}</td><td className="px-4 py-3">{count}</td></tr>})}</tbody></table></div>}
    </div>
  </div>
}
