import { Cable, CheckCircle2, CircleOff, ServerCog } from 'lucide-react'

const items=[
  {name:'Report ingestion',status:'Implemented',detail:'Server-side embedded text and workbook extraction for PDF, DOCX, XLSX, CSV and TXT. Sources are hashed and candidates remain pending.',ready:true},
  {name:'AI extraction provider',status:'Server-managed',detail:'Optional structured extraction through server-only configuration. Missing or failed providers fall back explicitly to deterministic extraction.',ready:true},
  {name:'Scanned-document OCR',status:'Not enabled',detail:'The accepted prototype explicitly did not require real OCR. Image-only PDFs fail without claiming extracted text.',ready:false},
  {name:'Primavera P6',status:'Not connected',detail:'No live P6 contract, credentials or accepted import workflow exists in the preserved prototype scope.',ready:false},
  {name:'Microsoft Project',status:'Not connected',detail:'No live Microsoft Project contract, credentials or accepted import workflow exists in the preserved prototype scope.',ready:false},
  {name:'Voice capture',status:'Not in final prototype scope',detail:'No preserved prototype voice workflow or trustworthy backend contract was found.',ready:false},
]

export default function IntegrationsStatusPage(){return <div className="h-full overflow-auto p-5 sm:p-8"><header><p className="text-[10px] font-bold uppercase tracking-[.12em]" style={{color:'#F46F29'}}>Capability truth</p><h1 className="mt-1 text-[24px] font-bold" style={{color:'var(--c-text)'}}>Integrations</h1><p className="mt-1 max-w-3xl text-[13px]" style={{color:'var(--c-muted)'}}>Implemented connections and explicit boundaries. No unavailable connector is presented as working.</p></header><div className="mt-6 grid gap-4 md:grid-cols-2">{items.map(item=><article key={item.name} className="rounded-[14px] p-5" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><div className="flex items-start gap-3">{item.ready?<CheckCircle2 size={18} style={{color:'#16A34A'}}/>:<CircleOff size={18} style={{color:'var(--c-subtle)'}}/>}<div><h2 className="text-[14px] font-semibold" style={{color:'var(--c-text)'}}>{item.name}</h2><p className="mt-1 text-[11px] font-bold uppercase tracking-wide" style={{color:item.ready?'#15803D':'#64748B'}}>{item.status}</p><p className="mt-3 text-[12px] leading-5" style={{color:'var(--c-muted)'}}>{item.detail}</p></div></div></article>)}</div><section className="mt-5 flex gap-3 rounded-[14px] p-5" style={{background:'var(--c-brand-tint)',border:'1px solid rgba(244,111,41,.2)'}}><ServerCog size={19} style={{color:'#F46F29'}}/><div><h2 className="text-[13px] font-semibold" style={{color:'var(--c-text)'}}>Security boundary</h2><p className="mt-1 text-[12px]" style={{color:'var(--c-muted)'}}>Provider keys remain server-side. The browser receives only validated extraction results, status and warnings.</p></div><Cable className="ml-auto hidden sm:block" size={22} style={{color:'#F46F29'}}/></section></div>}
