import { useMemo, useState } from 'react'
import { AlertTriangle, Bell, FileText, Search, X } from 'lucide-react'
import { useConnectedWorkspace } from '../hooks/useConnectedWorkspace'
import { attentionItems } from '../lib/connected-analytics'
import Modal from './ui/Modal'

interface Props { projectId:string; mode:'search'|'notifications'|null; onClose:()=>void; onNavigate:(route:string)=>void }

export default function ConnectedCommandCenter({projectId,mode,onClose,onNavigate}:Props){
  const state=useConnectedWorkspace(projectId);const [query,setQuery]=useState('')
  const workspace=state.workspace;const attention=workspace?attentionItems(workspace,new Date().toISOString().slice(0,10)):[]
  const results=useMemo(()=>{if(!workspace||!query.trim())return [];const needle=query.trim().toLowerCase();return [
    ...workspace.activities.filter(item=>[item.external_id,item.name,item.discipline,item.area,item.equipment_ref].some(value=>value?.toLowerCase().includes(needle))).map(item=>({id:`activity:${item.id}`,title:`${item.external_id} · ${item.name}`,detail:[item.discipline,item.area].filter(Boolean).join(' · '),route:'schedule',icon:'activity'})),
    ...(workspace.reports??[]).filter(item=>(item.filename??'manual field update').toLowerCase().includes(needle)||item.report_date.includes(needle)).map(item=>({id:`report:${item.id}`,title:item.filename??'Manual field update',detail:`Report · ${item.report_date}`,route:'reports',icon:'report'})),
    ...workspace.events.filter(item=>item.source_quote.toLowerCase().includes(needle)||item.actual_date?.includes(needle)).map(item=>({id:`event:${item.id}`,title:item.source_quote,detail:`${item.event_type.replace('_',' ')} · ${item.review_status}`,route:item.review_status==='pending'?'review-queue':'actuals',icon:'event'})),
  ].slice(0,30)},[workspace,query])
  if(!mode)return null
  function open(route:string){onNavigate(route);onClose()}
  return <Modal open={Boolean(mode)} onClose={onClose} aria-label={mode==='search'?'Search SENTINEL':'Project notifications'} zIndex={150}><section className="w-[min(620px,calc(100vw-32px))] overflow-hidden rounded-[16px]" style={{background:'var(--c-card)',border:'1px solid var(--c-border)',boxShadow:'var(--c-shadow-elevated)'}}><header className="flex items-center gap-3 border-b p-4" style={{borderColor:'var(--c-border)'}}>{mode==='search'?<Search size={17}/>:<Bell size={17}/>}<h2 className="flex-1 text-[15px] font-semibold" style={{color:'var(--c-text)'}}>{mode==='search'?'Search connected project':'Needs attention'}</h2><button onClick={onClose} aria-label="Close"><X size={17}/></button></header>
    {mode==='search'?<><div className="border-b p-4" style={{borderColor:'var(--c-border)'}}><label className="relative block"><Search className="absolute left-3 top-2.5" size={14} style={{color:'var(--c-subtle)'}}/><span className="sr-only">Search activities, reports and evidence</span><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-[9px] py-2 pl-9 pr-3 text-[13px]" style={{background:'var(--c-page)',border:'1px solid var(--c-border)',color:'var(--c-text)'}} placeholder="Activity ID, equipment, report or evidence text"/></label></div><div className="max-h-[430px] overflow-auto">{!query.trim()&&<p className="p-8 text-center text-[12px]" style={{color:'var(--c-muted)'}}>Search is scoped to the current connected project.</p>}{query.trim()&&results.length===0&&<p className="p-8 text-center text-[12px]" style={{color:'var(--c-muted)'}}>No connected records match this search.</p>}{results.map(item=><button key={item.id} onClick={()=>open(item.route)} className="flex w-full items-start gap-3 border-b px-4 py-3 text-left" style={{borderColor:'var(--c-border)'}}>{item.icon==='report'?<FileText size={15} style={{color:'#F46F29'}}/>:<Search size={15} style={{color:'#F46F29'}}/>}<span className="min-w-0 flex-1"><strong className="block truncate text-[12px]" style={{color:'var(--c-text)'}}>{item.title}</strong><span className="mt-0.5 block text-[11px]" style={{color:'var(--c-muted)'}}>{item.detail}</span></span></button>)}</div></>:<div className="max-h-[500px] overflow-auto">{state.loading&&<p className="p-8 text-center text-[12px]" style={{color:'var(--c-muted)'}}>Loading current attention conditions…</p>}{!state.loading&&attention.length===0&&<p className="p-8 text-center text-[12px]" style={{color:'var(--c-muted)'}}>No current attention conditions.</p>}{attention.map(item=><button key={item.id} onClick={()=>open(item.route)} className="flex w-full items-start gap-3 border-b px-4 py-3 text-left" style={{borderColor:'var(--c-border)'}}><AlertTriangle size={15} style={{color:'#D97706'}}/><span className="min-w-0 flex-1"><strong className="block truncate text-[12px]" style={{color:'var(--c-text)'}}>{item.entity}</strong><span className="mt-0.5 block text-[11px]" style={{color:'var(--c-muted)'}}>{item.label} · {item.reason}</span></span></button>)}</div>}
  </section></Modal>
}
