import { useMemo, useState } from 'react'
import { CheckCircle2, ChevronDown, RefreshCw, Search, Shield, X } from 'lucide-react'
import { useConnectedProject } from '../../context/ConnectedProjectContext'
import { useConnectedWorkspace } from '../../hooks/useConnectedWorkspace'
import type { AuditItem } from '../../lib/connected-types'
import { auditActionLabel, auditDetailFields, canViewAudit, filterAudit, formatAuditTimestamp, projectAudit } from '../../lib/real-audit'

function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void }) {
  return <div className="relative"><select value={value} onChange={event => onChange(event.target.value)} className="h-8 appearance-none rounded-[8px] pl-3 pr-8 text-[12px] outline-none" style={{ background: value ? 'var(--c-brand-tint)' : 'var(--c-card)', border: '1px solid var(--c-border)', color: value ? '#F46F29' : 'var(--c-muted)' }}><option value="">{label}</option>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown size={11} className="pointer-events-none absolute right-2.5 top-2.5" color="var(--c-muted)" /></div>
}

function AuditDetailDrawer({ item, projectName, currentUserId, timeZone, onClose }: { item: AuditItem; projectName: string; currentUserId: string | undefined; timeZone: string; onClose: () => void }) {
  const fields = auditDetailFields(item.detail)
  return <><button aria-label="Close audit detail" onClick={onClose} className="fixed inset-0 z-[90] cursor-default bg-black/20" /><aside role="dialog" aria-modal="true" aria-label="Audit record detail" className="fixed bottom-0 right-0 top-0 z-[100] flex w-full max-w-[430px] flex-col" style={{ background: 'var(--c-card)', borderLeft: '1px solid var(--c-border)', boxShadow: '-10px 0 34px rgba(0,0,0,.15)' }}>
    <header className="flex items-start justify-between border-b p-5" style={{ borderColor: 'var(--c-border)' }}><div><p className="text-[10px] font-bold uppercase tracking-[.08em]" style={{ color: '#F46F29' }}>Connected audit record</p><h2 className="mt-1 text-[18px] font-bold" style={{ color: 'var(--c-text)' }}>{auditActionLabel(item.action)}</h2><p className="mt-1 text-[11px]" style={{ color: 'var(--c-muted)' }}>{formatAuditTimestamp(item.created_at, timeZone)}</p></div><button onClick={onClose} aria-label="Close" className="flex h-8 w-8 items-center justify-center rounded-[8px]" style={{ color: 'var(--c-muted)' }}><X size={15} /></button></header>
    <div className="flex-1 overflow-auto p-5"><div className="mb-5 flex items-start gap-2 rounded-[10px] p-3" style={{ background: 'var(--c-page)', border: '1px solid var(--c-border)' }}><Shield size={14} className="mt-0.5 shrink-0" color="#64748B" /><p className="text-[11px] leading-5" style={{ color: 'var(--c-muted)' }}>Audit history is read-only and records connected workflow actions. This view provides recent history from the current API window.</p></div>
      {[['Audit ID',item.id],['Project',projectName],['Action',auditActionLabel(item.action)],['Record ID',item.record_id],['Actor',currentUserId === item.actor_id ? `Current user · ${item.actor_id}` : item.actor_id],['Timestamp',formatAuditTimestamp(item.created_at,timeZone)]].map(([label,value]) => <div key={label} className="border-b py-3" style={{ borderColor: 'var(--c-border)' }}><p className="text-[10px] font-bold uppercase tracking-[.07em]" style={{ color: 'var(--c-subtle)' }}>{label}</p><p className="mt-1 break-all text-[12px] font-medium" style={{ color: 'var(--c-text)', fontFamily: label.includes('ID') || label === 'Actor' ? 'var(--font-data)' : 'var(--font-ui)' }}>{value}</p></div>)}
      <h3 className="mb-1 mt-6 text-[10px] font-bold uppercase tracking-[.08em]" style={{ color: 'var(--c-subtle)' }}>Persisted detail</h3>{fields.length ? fields.map(field => <div key={field.key} className="border-b py-3" style={{ borderColor: 'var(--c-border)' }}><p className="text-[10px] font-bold uppercase tracking-[.07em]" style={{ color: 'var(--c-subtle)' }}>{field.label}</p><p className="mt-1 break-words text-[12px] leading-5" style={{ color: 'var(--c-text)' }}>{field.value}</p></div>) : <p className="py-3 text-[12px] italic" style={{ color: 'var(--c-muted)' }}>No simple detail fields were persisted for this record.</p>}
    </div>
  </aside></>
}

function ConnectedAuditLog() {
  const access = useConnectedProject()
  const project = access.project!
  const { workspace, loading, error, refresh } = useConnectedWorkspace(project.id)
  const [search, setSearch] = useState('')
  const [action, setAction] = useState<AuditItem['action'] | ''>('')
  const [actor, setActor] = useState('')
  const [date, setDate] = useState('')
  const [selected, setSelected] = useState<AuditItem | null>(null)
  const scoped = useMemo(() => projectAudit(project.id, workspace?.audit ?? []), [project.id, workspace])
  const actors = useMemo(() => [...new Set(scoped.map(item => item.actor_id))].sort(), [scoped])
  const filtered = useMemo(() => filterAudit(scoped, search, action, date).filter(item => !actor || item.actor_id === actor), [scoped, search, action, date, actor])
  const captured = scoped.filter(item => item.action === 'event_captured').length
  const verified = scoped.filter(item => item.action === 'actual_verified').length
  const membershipChanges = scoped.filter(item => item.action === 'membership_changed').length

  return <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
    <header className="shrink-0 border-b px-7 pb-4 pt-5" style={{ background: 'var(--c-page)', borderColor: 'var(--c-border)' }}><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.08em]" style={{ color: '#F46F29' }}>{project.name}</p><h1 className="text-[22px] font-bold" style={{ color: 'var(--c-text)' }}>Recent Audit History</h1><p className="text-[13px]" style={{ color: 'var(--c-muted)' }}>Persisted field captures, human verifications, and Team Access changes for this project.</p></div><button onClick={() => void refresh()} aria-label="Refresh audit history" className="flex h-9 items-center gap-2 rounded-[9px] px-3 text-[12px] font-semibold" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)', color: 'var(--c-muted)' }}><RefreshCw size={13} />Refresh</button></div>
      {!loading && !error && workspace && <div className="mt-4 flex flex-wrap items-center gap-5 text-[12px]" style={{ color: 'var(--c-muted)' }}><span><strong className="mr-1 text-[16px]" style={{ color: 'var(--c-text)' }}>{scoped.length}</strong>returned records</span><span><strong className="mr-1 text-[16px]" style={{ color: 'var(--c-text)' }}>{captured}</strong>field captures</span><span><strong className="mr-1 text-[16px]" style={{ color: 'var(--c-text)' }}>{verified}</strong>human verifications</span><span><strong className="mr-1 text-[16px]" style={{ color: 'var(--c-text)' }}>{membershipChanges}</strong>access changes</span><span className="ml-auto">Current API window · newest records first</span></div>}
      <div className="mt-4 flex flex-wrap gap-2"><div className="relative"><Search size={13} className="absolute left-3 top-2.5" color="var(--c-muted)" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search IDs, actors or details" className="h-8 w-60 rounded-[8px] pl-8 pr-3 text-[12px] outline-none" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)', color: 'var(--c-text)' }} /></div><FilterSelect label="All actions" value={action} onChange={value => setAction(value as AuditItem['action'] | '')} options={[{value:'event_captured',label:'Field Event Captured'},{value:'actual_verified',label:'Actual Verified'},{value:'membership_changed',label:'Membership Changed'}]} /><FilterSelect label="All actors" value={actor} onChange={setActor} options={actors.map(value => ({value,label:value}))} /><input type="date" aria-label="Filter by date" value={date} onChange={event => setDate(event.target.value)} className="h-8 rounded-[8px] px-3 text-[12px]" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)', color: 'var(--c-muted)' }} />{(search || action || actor || date) && <button onClick={() => { setSearch(''); setAction(''); setActor(''); setDate('') }} className="h-8 rounded-[8px] px-3 text-[12px] font-semibold" style={{ color: '#F46F29' }}>Clear filters</button>}</div>
    </header>
    {loading && <div className="p-12 text-center text-[13px]" style={{ color: 'var(--c-muted)' }}>Loading connected audit history…</div>}
    {!loading && error && <div role="alert" className="m-7 rounded-[12px] p-5 text-[13px]" style={{ background: '#FEF2F2', color: '#B91C1C' }}>{error}<button onClick={() => void refresh()} className="ml-3 font-bold underline">Retry</button></div>}
    {!loading && !error && workspace && <div className="min-h-0 flex-1 overflow-auto"><table className="w-full text-left" style={{ minWidth: 1040, borderCollapse: 'collapse' }}><thead className="sticky top-0 z-10" style={{ background: 'var(--c-page)' }}><tr>{['Timestamp','Action','Record ID','Actor ID','Persisted detail'].map(label => <th key={label} className="border-b px-5 py-3 text-[10px] font-bold uppercase tracking-[.08em]" style={{ borderColor: 'var(--c-border)', color: 'var(--c-subtle)' }}>{label}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.id} onClick={() => setSelected(item)} tabIndex={0} role="button" onKeyDown={event => { if (event.key === 'Enter') setSelected(item) }} className="cursor-pointer border-b" style={{ borderColor: 'var(--c-border)' }}><td className="px-5 py-4 text-[12px]" style={{ color: 'var(--c-muted)', whiteSpace: 'nowrap' }}>{formatAuditTimestamp(item.created_at, project.timezone)}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-[11px] font-bold" style={{ color: item.action === 'actual_verified' ? '#15803D' : '#C2410C', background: item.action === 'actual_verified' ? 'rgba(22,163,74,.10)' : 'rgba(244,111,41,.11)' }}>{item.action === 'actual_verified' && <CheckCircle2 size={11} />}{auditActionLabel(item.action)}</span></td><td className="px-5 py-4 text-[11px]" style={{ color: 'var(--c-text)', fontFamily: 'var(--font-data)' }}>{item.record_id}</td><td className="px-5 py-4 text-[11px]" style={{ color: 'var(--c-muted)', fontFamily: 'var(--font-data)' }}>{access.identity?.user.id === item.actor_id ? <><strong style={{ color: 'var(--c-text)' }}>Current user</strong><br />{item.actor_id}</> : item.actor_id}</td><td className="px-5 py-4 text-[11px]" style={{ color: 'var(--c-muted)' }}>{auditDetailFields(item.detail).slice(0,2).map(field => `${field.label}: ${field.value}`).join(' · ') || 'No simple detail fields'}</td></tr>)}</tbody></table>{!filtered.length && <div className="p-12 text-center"><h2 className="text-[16px] font-bold" style={{ color: 'var(--c-text)' }}>{scoped.length ? 'No audit records match these filters' : 'No persisted audit records'}</h2><p className="mt-1 text-[13px]" style={{ color: 'var(--c-muted)' }}>{scoped.length ? 'Clear the filters to see the returned history.' : 'This project has no audit records in the current API window.'}</p></div>}</div>}
    {selected && <AuditDetailDrawer item={selected} projectName={project.name} currentUserId={access.identity?.user.id} timeZone={project.timezone} onClose={() => setSelected(null)} />}
  </div>
}

export default function AuditLogPage() {
  const access = useConnectedProject()
  if (!canViewAudit(access.role)) return <div className="flex flex-1 items-center justify-center p-8"><section className="max-w-md rounded-[16px] p-7 text-center" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)' }}><Shield size={24} className="mx-auto mb-3" color="#64748B" /><h1 className="text-[20px] font-bold" style={{ color: 'var(--c-text)' }}>Audit history is restricted</h1><p className="mt-2 text-[13px] leading-5" style={{ color: 'var(--c-muted)' }}>This project role cannot view audit records. Audit access is available to Planner, Project Controls, and Administrator memberships.</p></section></div>
  return <ConnectedAuditLog />
}
