import { useCallback, useEffect, useRef, useState } from 'react'
import { Plus, RefreshCw, Search, ShieldCheck, UserRoundX } from 'lucide-react'
import { useConnectedProject } from '../../context/ConnectedProjectContext'
import { assignProjectMember, getProjectMembers, updateProjectMember } from '../../lib/connected-api'
import { PROJECT_ROLES, type ManagedProjectMember, type ProjectRole } from '../../lib/connected-types'
import { canManageTeam, isExactAccountEmail, PROJECT_ROLE_LABELS, wouldRemoveLastAdministrator } from '../../lib/real-admin'

export default function AdminPage(){
  const access=useConnectedProject(); const projectId=access.project!.id
  const [members,setMembers]=useState<ManagedProjectMember[]>([]); const [loading,setLoading]=useState(true)
  const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [query,setQuery]=useState('')
  const [email,setEmail]=useState(''); const [role,setRole]=useState<ProjectRole>('site-supervisor'); const [adding,setAdding]=useState(false)
  const [busy,setBusy]=useState(''); const [draftRoles,setDraftRoles]=useState<Record<string,ProjectRole>>({}); const generation=useRef(0)

  const load=useCallback(async()=>{const current=++generation.current;setMembers([]);setLoading(true);setError('');try{const result=await getProjectMembers(projectId);if(current===generation.current){setMembers(result.members);setDraftRoles(Object.fromEntries(result.members.map(member=>[member.user_id,member.role])))}}catch(cause){if(current===generation.current)setError(cause instanceof Error?cause.message:'Unable to load Team Access.')}finally{if(current===generation.current)setLoading(false)}},[projectId])
  useEffect(()=>{if(canManageTeam(access.role))void load();else{setMembers([]);setLoading(false)}return()=>{generation.current++}},[access.role,load])
  if(!canManageTeam(access.role))return <div className="p-8"><div className="max-w-xl rounded-[14px] p-6" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><ShieldCheck size={22} style={{color:'#F46F29'}}/><h1 className="mt-3 text-[22px] font-bold" style={{color:'var(--c-text)'}}>Administrator access required</h1><p className="mt-2 text-[13px]" style={{color:'var(--c-muted)'}}>Team Access is available only to an active Administrator of this project.</p></div></div>
  const filtered=members.filter(member=>`${member.email} ${PROJECT_ROLE_LABELS[member.role]} ${member.active?'active':'inactive'}`.toLowerCase().includes(query.trim().toLowerCase()))
  async function addMember(){if(!isExactAccountEmail(email)){setError('Enter the exact email address of an existing SENTINEL account.');return}setBusy('add');setError('');setMessage('');try{await assignProjectMember(projectId,{email:email.trim().toLowerCase(),role});setEmail('');setAdding(false);setMessage('Project access was saved.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to assign project access.')}finally{setBusy('')}}
  async function saveMember(member:ManagedProjectMember,nextActive=member.active){const nextRole=draftRoles[member.user_id]??member.role;if(wouldRemoveLastAdministrator(member,nextRole,nextActive,members)){setError('Every project must retain at least one active Administrator.');return}setBusy(member.user_id);setError('');setMessage('');try{await updateProjectMember(projectId,member.user_id,{role:nextRole,active:nextActive});setMessage(nextActive?'Membership was updated.':'Project access was deactivated.');await Promise.all([load(),access.refresh()])}catch(cause){setError(cause instanceof Error?cause.message:'Unable to update project access.')}finally{setBusy('')}}
  return <div className="admin-page min-h-full overflow-auto p-8">
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.1em]" style={{color:'#F46F29'}}>Administration</p><h1 className="mt-1 text-[26px] font-bold" style={{color:'var(--c-text)'}}>Team Access</h1><p className="mt-1 text-[13px]" style={{color:'var(--c-muted)'}}>Manage real membership for {access.project?.name}. Users must already have a SENTINEL account.</p></div><button onClick={()=>setAdding(value=>!value)} className="flex items-center gap-2 rounded-[9px] px-4 py-2 text-[12px] font-semibold text-white" style={{background:'linear-gradient(135deg,#F46F29,#F59B4C)'}}><Plus size={14}/>Add project member</button></div>
    {error&&<div role="alert" className="mb-4 rounded-[10px] p-3 text-[12px] text-red-700" style={{background:'rgba(220,38,38,.08)'}}>{error}</div>}{message&&<div role="status" className="mb-4 rounded-[10px] p-3 text-[12px] text-green-700" style={{background:'rgba(22,163,74,.08)'}}>{message}</div>}
    {adding&&<section className="mb-5 grid gap-3 rounded-[14px] p-5 md:grid-cols-[1fr_220px_auto]" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><label className="text-[11px] font-semibold" style={{color:'var(--c-muted)'}}>EXACT ACCOUNT EMAIL<input value={email} onChange={event=>setEmail(event.target.value)} type="email" placeholder="person@example.com" className="mt-1 h-10 w-full rounded-[8px] px-3 text-[13px]" style={{background:'var(--c-page)',border:'1px solid var(--c-border)',color:'var(--c-text)'}}/></label><label className="text-[11px] font-semibold" style={{color:'var(--c-muted)'}}>PROJECT ROLE<select value={role} onChange={event=>setRole(event.target.value as ProjectRole)} className="mt-1 h-10 w-full rounded-[8px] px-3 text-[13px]" style={{background:'var(--c-page)',border:'1px solid var(--c-border)',color:'var(--c-text)'}}>{PROJECT_ROLES.map(item=><option key={item} value={item}>{PROJECT_ROLE_LABELS[item]}</option>)}</select></label><button disabled={busy==='add'} onClick={()=>void addMember()} className="self-end rounded-[8px] px-4 py-2.5 text-[12px] font-semibold text-white disabled:opacity-50" style={{background:'#F46F29'}}>{busy==='add'?'Saving…':'Assign access'}</button></section>}
    <section className="rounded-[14px]" style={{background:'var(--c-card)',border:'1px solid var(--c-border)'}}><div className="flex items-center gap-3 border-b p-4" style={{borderColor:'var(--c-border)'}}><div className="relative max-w-sm flex-1"><Search size={14} className="absolute left-3 top-2.5" style={{color:'var(--c-muted)'}}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search email, role or status" className="h-9 w-full rounded-[8px] pl-9 pr-3 text-[12px]" style={{background:'var(--c-page)',border:'1px solid var(--c-border)',color:'var(--c-text)'}}/></div><button onClick={()=>void load()} aria-label="Refresh members"><RefreshCw size={15} style={{color:'var(--c-muted)'}}/></button></div>
      {loading?<p className="p-5 text-[13px]" style={{color:'var(--c-muted)'}}>Loading project members…</p>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b" style={{borderColor:'var(--c-border)'}}>{['EMAIL','ROLE','ACCESS STATUS','ACTIONS'].map(label=><th key={label} className="px-5 py-3 text-[10px] font-bold tracking-[.08em]" style={{color:'var(--c-subtle)'}}>{label}</th>)}</tr></thead><tbody>{filtered.map(member=><tr key={member.user_id} className="border-b last:border-0" style={{borderColor:'var(--c-border)'}}><td className="px-5 py-4"><div className="text-[12px] font-semibold" style={{color:'var(--c-text)'}}>{member.email}</div><div className="mt-0.5 font-mono text-[9px]" style={{color:'var(--c-subtle)'}}>{member.user_id}</div></td><td className="px-5 py-4"><select value={draftRoles[member.user_id]??member.role} onChange={event=>setDraftRoles(current=>({...current,[member.user_id]:event.target.value as ProjectRole}))} className="h-9 rounded-[8px] px-2 text-[12px]" style={{background:'var(--c-page)',border:'1px solid var(--c-border)',color:'var(--c-text)'}}>{PROJECT_ROLES.map(item=><option key={item} value={item}>{PROJECT_ROLE_LABELS[item]}</option>)}</select></td><td className="px-5 py-4"><span className="rounded-full px-2 py-1 text-[10px] font-semibold" style={{background:member.active?'rgba(22,163,74,.09)':'rgba(100,116,139,.1)',color:member.active?'#16A34A':'#64748B'}}>{member.active?'Active':'Inactive'}</span></td><td className="px-5 py-4"><div className="flex gap-3"><button disabled={busy===member.user_id||(draftRoles[member.user_id]??member.role)===member.role} onClick={()=>void saveMember(member)} className="text-[11px] font-semibold disabled:opacity-35" style={{color:'#F46F29'}}>Save role</button><button disabled={busy===member.user_id} onClick={()=>void saveMember(member,!member.active)} className="flex items-center gap-1 text-[11px] font-semibold disabled:opacity-35" style={{color:member.active?'#DC2626':'#16A34A'}}>{member.active&&<UserRoundX size={12}/>} {member.active?'Deactivate':'Reactivate'}</button></div></td></tr>)}{filtered.length===0&&<tr><td colSpan={4} className="p-8 text-center text-[12px]" style={{color:'var(--c-muted)'}}>No project members match this view.</td></tr>}</tbody></table></div>}
    </section>
    <p className="mt-4 text-[11px]" style={{color:'var(--c-subtle)'}}>Membership changes are project-scoped, audited, and checked by the backend. The last active Administrator cannot be removed or demoted.</p>
  </div>
}
